### ISSUE TITLE
Inventory Tweak (sort inventory)

### ISSUE THREAD

**Issue by JOOHHN69** [xKeksbyte/icarus-issue-tracker#1]
1. Manchmal sortiert es das Inventar nicht richtig und lässt das schwert auf irgendeinem Slot liegen.

2. Wenn man z.B 2 schwerter hat, das eine Gold und das andere iron und beide die selbe sharpness haben, dann kann sich der InventorySorter nicht entscheiden und switched ständig hin und her.

**Comment by xKeksbyte** [comment]
Das weiß ich schon, Versuche es später mal zu fixen

**Comment by xKeksbyte** [comment]
Fixed in der neuen version - bald release
