### ISSUE TITLE
[Icarus] Cubecraft Scaffoldwalk Autobannt bei langer Benutztung (Cubecraft Config)

### ISSUE THREAD

**Issue by JakobsCode** [xKeksbyte/icarus-issue-tracker#11]
Moin Moin,

Habe jetzt mal auf Cubecraft den Scaffoldwalk für 40s genutzt (habe bisschen übertrieben), danach wurde ich instant geautobannt. Ein Alt weniger xD

Bis danne,
Jakob

**Comment by xKeksbyte** [comment]
Weil wir noch keine cubecraft scaffold settings haben

Ich werde mich heute dran setzen scaffold settings zu machen :D 
Benutz btw den glide

**Comment by xKeksbyte** [comment]
fixed
