### ISSUE TITLE
[Ircaus] Nutzt Truhen als Blöcke beim Tower

### ISSUE THREAD

**Issue by JakobsCode** [xKeksbyte/icarus-issue-tracker#12]
Moin,

Beim Tower nutzt der Client auch gerne Truhen um sich hochzubauen. Funktioniert natürlich nicht :)

Mit freundlichen Grüßen,
Jakob

**Comment by xKeksbyte** [comment]
fixed ^^

**Comment by JakobsCode** [comment]
Ehrenmann!

**Comment by xKeksbyte** [comment]
neue version kommt bald ^^

**Comment by JakobsCode** [comment]
Hyped i guess
