### ISSUE TITLE
[Icarus] Gomme Killaura crasht GommeHD.net 1v1 Lobbys xD

### ISSUE THREAD

**Issue by JakobsCode** [xKeksbyte/icarus-issue-tracker#13]
Moin,

du glaubst es nicht, aber mit der Killaura kann man die 1v1 Lobbys auf GommeHD.net crashen. Hier habe ich das mal aufgenommen und ungelisted hochgeladen: https://youtu.be/t5dATq_TP3s
Vielleicht gleich einen Gomme Crasher draus machen xD

Mit freundlichen Grüßen,
Jakob

**Comment by xKeksbyte** [comment]
crasher dürfen wir actually nicht in den client packen weil es ein DOS ist und somit illegal ist, sonst hätte ich schon 20 crasher modes drin lmao

**Comment by JakobsCode** [comment]
Frech! Lmao
