### ISSUE TITLE
Altmanager (TheAltening)

### ISSUE THREAD

**Issue by JOOHHN69** [xKeksbyte/icarus-issue-tracker#2]
Der api-token wird nicht gespeichert nach einem neustart von Icarus.

Und der reconnect button funktioniert nicht.

kein issue: Es wäre nice, wenn man nachdem man gebannt wurde einfach einen neuen alt generieren könnte ohne in den alt manager zu gehen.

**Comment by xKeksbyte** [comment]
> kein issue: Es wäre nice, wenn man nachdem man gebannt wurde einfach einen neuen alt generieren könnte ohne in den alt manager zu gehen.
Das hatte ich eh vor :p

>Der api-token wird nicht gespeichert nach einem neustart von Icarus.

Das ist mir bewusst und ist auch kein bug ^^

>Und der reconnect button funktioniert nicht.

Muss ich nochmal nach schauen

**Comment by xKeksbyte** [comment]
//fixed
