### ISSUE TITLE
Config section

### ISSUE THREAD

**Issue by JOOHHN69** [xKeksbyte/icarus-issue-tracker#3]
Nach dem update haben sich die configs verdoppelt. https://i.imgur.com/rcLZvYf.png

**Comment by JOOHHN69** [comment]
Kein bock neuen thread aufzumachen, aber noslowdown lässt mich nicht mehr essen auch wenn ich nur eating ausmache. Ich muss das komplett ausmachen, hab es getestet auf cubecraft keine Ahnung wie das auf anderen Servern ist, mein Ping ist auch ok.

Edit: es funktioniert nur wenn ich 'Packets' ausschalte.

**Comment by xKeksbyte** [comment]
lösch einfach mal den config ordner werde das auch später noch fixen
