### ISSUE TITLE
Modes umstellen 

### ISSUE THREAD

**Issue by lePerseus** [xKeksbyte/icarus-issue-tracker#6]
Man kann z.B. bei Fly den Mode nicht umstellen, da die Einstellungen nicht mehr im Bildschirm sind. Außerdem kann man manche Configs im Gui nicht auswählen und sich auch weder per Command, noch im Gui löschen.

**Comment by JOOHHN69** [comment]
schon versucht in die mc einstellungen zu gehen und gui scale auf normal zu tun ?

**Comment by lePerseus** [comment]
Meinst du im Gui? Beim Module Gui?

**Comment by lePerseus** [comment]
Das geht aber Trotzdem sollte man Scrollen können

**Comment by JakobsCode** [comment]
Bypass Flys sind bei Glide xD

**Comment by xKeksbyte** [comment]
Mach halt guiscale auf small :) wir werden vielleicht bald eine einstellung hinzu fügen das du die größe einstellbar machen kannst im clickgui
