### ISSUE TITLE
[Icarus] Hypixel Fly autobannet!

### ISSUE THREAD

**Issue by JakobsCode** [xKeksbyte/icarus-issue-tracker#9]
Hallo,
Der Hypixel Glide in der Hypixel Config autobannet nach wenigen Sekunden. Ein Alt weniger xD
Mit freundlichen Grüßen,
Jakob

**Comment by xKeksbyte** [comment]
Das wissen wir bereits und wir haben es auch schon mehrmals gesagt das wir kein hypixel fly atm haben :P 
Warte einfach erstmal ab wir machen grade nichts für hypixel, aber bald c:
